//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// LoginPage class.
/// </summary>
/// <remarks>
/// Auto-generated class.
/// </remarks>
public partial class LoginPage {

   /// <summary>
   /// Head1 control.
   /// </summary>
   /// <remarks>
   /// Auto-generated field.
   /// To modify move field declaration from designer file to code-behind file.
   /// </remarks>
   protected global::System.Web.UI.HtmlControls.HtmlHead Head1;

   /// <summary>
   /// ProgressControl control.
   /// </summary>
   /// <remarks>
   /// Auto-generated field.
   /// To modify move field declaration from designer file to code-behind file.
   /// </remarks>
   protected global::DevExpress.ExpressApp.Web.Controls.ProgressControl ProgressControl;

   /// <summary>
   /// ViewCaption control.
   /// </summary>
   /// <remarks>
   /// Auto-generated field.
   /// To modify move field declaration from designer file to code-behind file.
   /// </remarks>
   protected global::System.Web.UI.WebControls.Literal ViewCaption;

   /// <summary>
   /// form1 control.
   /// </summary>
   /// <remarks>
   /// Auto-generated field.
   /// To modify move field declaration from designer file to code-behind file.
   /// </remarks>
   protected global::System.Web.UI.HtmlControls.HtmlForm form1;

   /// <summary>
   /// ErrorInfo control.
   /// </summary>
   /// <remarks>
   /// Auto-generated field.
   /// To modify move field declaration from designer file to code-behind file.
   /// </remarks>
   protected global::DevExpress.ExpressApp.Web.Templates.Controls.ErrorInfoControl ErrorInfo;

   /// <summary>
   /// ViewSite control.
   /// </summary>
   /// <remarks>
   /// Auto-generated field.
   /// To modify move field declaration from designer file to code-behind file.
   /// </remarks>
   protected global::System.Web.UI.WebControls.PlaceHolder ViewSite;

   /// <summary>
   /// PopupActions control.
   /// </summary>
   /// <remarks>
   /// Auto-generated field.
   /// To modify move field declaration from designer file to code-behind file.
   /// </remarks>
   protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.HorizontalActionContainer PopupActions;
}
