'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Default class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class [Default]

	'''<summary>
	'''ProgressControl control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ProgressControl As Global.DevExpress.ExpressApp.Web.Controls.ProgressControl

	'''<summary>
	'''form1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

	'''<summary>
	'''ApplicationTitle control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ApplicationTitle As Global.System.Web.UI.WebControls.HyperLink

	'''<summary>
	'''InfoMessagesPanel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents InfoMessagesPanel As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''NavigationTabsActionContainer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents NavigationTabsActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.NavigationTabsActionContainer

	'''<summary>
	'''ViewTitle control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ViewTitle As Global.System.Web.UI.WebControls.Table

	'''<summary>
	'''TableRow1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TableRow1 As Global.System.Web.UI.WebControls.TableRow

	'''<summary>
	'''TableCell1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TableCell1 As Global.System.Web.UI.WebControls.TableCell

	'''<summary>
	'''SearchActionContainer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents SearchActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.HorizontalActionContainer

	'''<summary>
	'''RecordsNavigationContainer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RecordsNavigationContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.HorizontalActionContainer

	'''<summary>
	'''TableCell2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TableCell2 As Global.System.Web.UI.WebControls.TableCell

	'''<summary>
	'''ViewImage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ViewImage As Global.System.Web.UI.WebControls.Image

	'''<summary>
	'''ViewCaption control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ViewCaption As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ViewsHistoryNavigationContainer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ViewsHistoryNavigationContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.NavigationHistoryActionContainer

	'''<summary>
	'''VerticalNewActionContainer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents VerticalNewActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.VerticalActionContainer

	'''<summary>
	'''VerticalToolsActionContainer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents VerticalToolsActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.VerticalActionContainer

	'''<summary>
	'''ContextObjectsCreationActionContainer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ContextObjectsCreationActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.HorizontalActionContainer

	'''<summary>
	'''ListViewDataManagementActionContainer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ListViewDataManagementActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.HorizontalActionContainer

	'''<summary>
	'''TopRecordEditActionContainer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents TopRecordEditActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.HorizontalActionContainer

	'''<summary>
	'''ViewPresentationActionContainer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ViewPresentationActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.HorizontalActionContainer

	'''<summary>
	'''ErrorInfo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ErrorInfo As Global.DevExpress.ExpressApp.Web.Templates.Controls.ErrorInfoControl

	'''<summary>
	'''Table1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Table1 As Global.System.Web.UI.WebControls.Table

	'''<summary>
	'''ViewSite control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ViewSite As Global.System.Web.UI.WebControls.TableCell

	'''<summary>
	'''BottomRecordEditActionContainer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents BottomRecordEditActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.HorizontalActionContainer

	'''<summary>
	'''NavigationLinksActionContainer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents NavigationLinksActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.NavigationLinksActionContainer

	'''<summary>
	'''Copyright control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Copyright As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''DiagnosticActionContainer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents DiagnosticActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.WrappedHorizontalActionContainer

	'''<summary>
	'''LogoImage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LogoImage As Global.System.Web.UI.WebControls.Image
End Class
