'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''ErrorPage class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class ErrorPage

	'''<summary>
	'''Head1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

	'''<summary>
	'''form1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

	'''<summary>
	'''ApplicationTitle control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ApplicationTitle As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''InfoMessagesPanel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents InfoMessagesPanel As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''ErrorTitleLiteral control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ErrorTitleLiteral As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''ErrorPanel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ErrorPanel As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''ReportResult control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ReportResult As Global.System.Web.UI.WebControls.PlaceHolder

	'''<summary>
	'''ApologizeMessage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ApologizeMessage As Global.System.Web.UI.WebControls.PlaceHolder

	'''<summary>
	'''RequestUrl control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RequestUrl As Global.System.Web.UI.WebControls.HyperLink

	'''<summary>
	'''HyperLink1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents HyperLink1 As Global.System.Web.UI.WebControls.HyperLink

	'''<summary>
	'''LiteralReturn control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LiteralReturn As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''HyperLinkReturn control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents HyperLinkReturn As Global.System.Web.UI.WebControls.HyperLink

	'''<summary>
	'''RequestUrl2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RequestUrl2 As Global.System.Web.UI.WebControls.HyperLink

	'''<summary>
	'''Details control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Details As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''DetailsText control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents DetailsText As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''ReportForm control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ReportForm As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''DescriptionTextBox control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents DescriptionTextBox As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''ReportButton control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ReportButton As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''Copyright control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Copyright As Global.System.Web.UI.WebControls.Literal

	'''<summary>
	'''LogoImage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LogoImage As Global.System.Web.UI.WebControls.Image
End Class
