'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''NestedFrameControl class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class NestedFrameControl

	'''<summary>
	'''ViewImage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ViewImage As Global.System.Web.UI.WebControls.Image

	'''<summary>
	'''ViewCaption control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ViewCaption As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ContextObjectsCreationActionContainer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ContextObjectsCreationActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.HorizontalActionContainer

	'''<summary>
	'''RecordEditContainer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RecordEditContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.HorizontalActionContainer

	'''<summary>
	'''ViewContainer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ViewContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.HorizontalActionContainer

	'''<summary>
	'''DiagnosticActionContainer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents DiagnosticActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.HorizontalActionContainer

	'''<summary>
	'''ViewSite control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ViewSite As Global.System.Web.UI.WebControls.Panel
End Class
